### PR TITLE
eliminated fetchprojectData in the webcomponent and now uses the fetc…

### LINKED ISSUE #31: Use fetchprojectData.js in web-component.js to maintain code reusability
image

Here in web-component.js same functionality of code is being called again implemented ensure you the fetchprojectData.js instead.

### PR DESCRIPTION
**Pull request by sarah-fidahussain-SLU**
Fixes #31 

What was changed: There was a separate fetchData function and a fetchData function built in the web-component. To maintain code reusability I eliminated the fetchData function that was built in the web-component and used the existing fetchData function that was separate.
Why was it changed: This was to eliminate code duplicates and reduce confusion on which one to use.
How was it changed:
- web-component.js: Eliminated the fetchData function that was built-in and it is now more stream-lined by using the imported function.

### CODE REVIEW

**Review by Matthew-Clendenning — CHANGES_REQUESTED** [review]
Good job reducing redundancy; however, it seems like this file is a repeat of what fetchProjectData is doing already. Maybe we should remove one of the two files.

**Comment by MutyaSowmya123** [comment]
> Good job reducing redundancy; however, it seems like this file is a repeat of what fetchProjectData is doing already. Maybe we should remove one of the two files.

Yes, check for the functionality that is being repeated and delete one of the file. Implementing (if required ) some things from one of the files.

**Review by MutyaSowmya123 — CHANGES_REQUESTED** [review]
Check for the functionalities that are implemented by both the files and ensure the required once are retained.

**Comment by sarah-fidahussain-SLU** [comment]
I have deleted the other fetchProjectData file as that had outdated and hard-coded tokens.

**Review by MutyaSowmya123 — APPROVED** [review]

**Pull request merged**
